mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.chunfeng.emsystem.mybatis.entity
# 应用服务 WEB 访问端口
server:
  port: 8080
#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13597803422dw